name: Calculator api tests

on:
  pull_request:
    branches:
      - test

jobs:
  test-calculator-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Build Docker image
        run: docker build -t calculator-app .

      - name: Run Docker image
        run: docker run -d -p 8000:8000 calculator-app

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Run tests
        run: pytest tests/calculator_api_test.py
