on:
  pull_request:
    branches:
      - test
    types:
      - closed

jobs:
  checkout:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

  run-tests:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Functional Tests
      uses: ./.github/workflows/api_tests.yaml

  push-dockerfile:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub and push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker build -t calculator-app .
        docker tag calculator-app ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/calculator-app:latest
